### ISSUE TITLE
thoughts?

### ISSUE THREAD

**Issue by v1k0d3n** [davidkbainbridge/k8s-playground#6]
@davidkbainbridge and @errordeveloper: can you guys weigh in on this repo (your thoughts)?
https://github.com/att-comdev/halcyon-vagrant-kubernetes (vagrant portion with halcyon submodule)
https://github.com/att-comdev/halcyon-kubernetes (just the ansible playbook to keep things clean)

we've been trying to accommodate several people in our vagrant deployment, which is similar to yours here. i understand if you want to keep your own, but merging efforts would be great if you have any requirements above what we're offering? some of the plus sides are:

* separation of the ansible playbook and vagrant deployment (less confusing for folks who don't realize this can be used directly to other external cloud providers).
* vagrant deployment supports local (virtualbox and libvirt), direct to openstack provider, and soon aws provider.
* user-defined cpu/memory
* user-defined naming convention
* user-defined sdn ranges
* user-defined nat/public interfaces
* ansible supports centos/ubuntu (coreos coming soon)
* bring your own token
* any of the popular son's (weave default, calico, canal, romana)
* any number of kubernetes nodes can be deployed (variable)
* add-ons supported (currently, kube-dashboard and helm with future kpm, prometheus and others)
* configure the vagrant host for kubectl and helm
* maybe more i can't think of off the top of my head? :)

let me know if any of this is useful, and if you want to collaborate or have any suggestions/improvements we can work on together. sorry i didn't call yet...with the os summit in barcelona and kubecon, i've been out of my mind and buried with catch-up work. we're going to write some documentation around this project for the openstack koala-kubernetes team (this is why we started our repo). it was nice to see yours as well! try it out, and please offer any feedback!

- v1k

**Comment by davidkbainbridge** [comment]
Comments after a quick look at reading the above.

I agree with the goals you have stated above and see the value in have a single definitive example including the separation of bringing up VMs (vagrant) from deploying K8s; thus enabling the K8s deployment playbooks to be used against physical servers as well.

The only thing I see missing above this is examples of running the system and verifying that it is operational, including examples of creating a service, pod etc. and host to access those services via DNS and how fail-over works. This is actually where I have been putting more focus lately as I can do similar examples in both K8s and Swarm + Registrar + Consul.

To be honest, this repo was started as a project to experiment in the deployment of K8s v. Swarm and understand the them in terms of a comparison, which is why I think examples above base deployment is key.

I would be curious about any conversations around this that happened at Kubecon.

**Comment by v1k0d3n** [comment]
we can sync-up/talk if you want. if you want to have some examples included in a kubeadm/vagrant deployment, and feel that's missing from our solution...i would be happy to add it as an optional item. it would be nice to have everyone working in one place; and honestly, i don't care if that "place" is here, or ours. i would honestly prefer for it to be up in Kubernetes if there was any value in this (not sure there really is though).

**Comment by davidkbainbridge** [comment]
I don't particularly care where it reside either. Not sure I understand your last comment about "if there is any value in this"? Are you referring that there may not be value in having the ansible scripts in the kubernetes repo? I would think there is as it would be an example and a base from which people can easily bring up a cluster. 

I suspect the actual location is less important than a clear path to get them so that people have a learning path that quickly gets them up and running a cluster.

**Comment by v1k0d3n** [comment]
well, not sure if Kubernetes wants to be home to a vagrant demo project, since there is already a project like minikube. @errordeveloper is deep into this understanding though as a kubeadm contributor/core. your thoughts Ilya? for us, we need a multi-vagrant demo for some of our testing (quorum of 3), but a quorum is still 1 also...so most people are fine with minikube. but hey, if kubernetes ever wanted it or finds use with it...i'm totally fine with it.

**Comment by v1k0d3n** [comment]
@davidkbainbridge if you want, we can close this issue. it's been open for a while. we've since been able to configure minikube for our [project](https://github.com/att-comdev/openstack-helm/blob/master/docs/developer/minikube.md), but we'll continue to maintain [vagrant-halcyon](https://github.com/att-comdev/halcyon-vagrant-kubernetes) (and it's [halcyon-kubernetes submodule](https://github.com/att-comdev/halcyon-kubernetes)) because it is being officially used by an [openstack project](https://github.com/openstack/kolla-kubernetes/blob/master/doc/source/development-environment.rst#setup-environment).

if you want to join  and bring whatever you need to the project, we're completely open to it (including verification of the cluster). we've added CI for PR's, but are admittedly improving things as gaps are found. halcyon added [ceph pvc support](https://github.com/att-comdev/halcyon-kubernetes/blob/master/kube-deploy/group_vars/all.yml#L57-L62), even thought the requirements are fairly extreme (as our ceph charts are designed to be production-ready, and not resource friendly for vagrant installs). at least it's an optional item. either way, if you need anything from the project you are welcome to add them so there are no gaps in what you need.

**Comment by dbainbri-ciena** [comment]
ok, let me close this issue. I will take a look at the other projects.

**Comment by dbainbri-ciena** [comment]
close #6

**Comment by davidkbainbridge** [comment]
I will close and look into the other repos.
